[package]
name = "learn-rust"
version = "0.1.0"
authors = ["Hans Yuan <hansy@surveymonkey.com>"]
edition = "2018"

[dependencies]
rand = "0.7"


[[bin]]
name = "ch2/binary-trees"
path = "ch2/binary-trees.rs"